// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGpJeWBgYOPUIG-E9GZLNWecqaVFoBNA',
    appId: '1:141872790596:web:5d08b3d90c05b5e1205011',
    messagingSenderId: '141872790596',
    projectId: 'heyworkoriginal',
    authDomain: 'heyworkoriginal.firebaseapp.com',
    storageBucket: 'heyworkoriginal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEM__GmyYvgTwQnajP1jBhNZKDwz67Ac',
    appId: '1:141872790596:android:38d1f70446347cca205011',
    messagingSenderId: '141872790596',
    projectId: 'heyworkoriginal',
    storageBucket: 'heyworkoriginal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQc_OPoo5MwKgpKnGq7Ga9XavsO0yh22I',
    appId: '1:141872790596:ios:f215597a6842dd71205011',
    messagingSenderId: '141872790596',
    projectId: 'heyworkoriginal',
    storageBucket: 'heyworkoriginal.firebasestorage.app',
    iosBundleId: 'com.example.heyWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQc_OPoo5MwKgpKnGq7Ga9XavsO0yh22I',
    appId: '1:141872790596:ios:f215597a6842dd71205011',
    messagingSenderId: '141872790596',
    projectId: 'heyworkoriginal',
    storageBucket: 'heyworkoriginal.firebasestorage.app',
    iosBundleId: 'com.example.heyWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGpJeWBgYOPUIG-E9GZLNWecqaVFoBNA',
    appId: '1:141872790596:web:b30caba7b732969a205011',
    messagingSenderId: '141872790596',
    projectId: 'heyworkoriginal',
    authDomain: 'heyworkoriginal.firebaseapp.com',
    storageBucket: 'heyworkoriginal.firebasestorage.app',
  );
}
